apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-ci-cd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-ci-cd-app
  template:
    metadata:
      labels:
        app: java-ci-cd-app
    spec:
      containers:
      - name: java-app
        image: youracr.azurecr.io/java-ci-cd-app:latest
        ports:
        - containerPort: 8081
