apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: <existing-public-ip>
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
