apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30036  # choose a port between 30000-32767
